export const PLAN_AND_LIMITS = {
  HOBBY: {
    name: "Hobby",
    type: "hobby",
    price_monthly: 0,
    price_yearly: 0,
    currency: "USD",
    max_monitors: 2,
    max_cron_jobs: 1,
    max_team_members: 1,
    max_workspaces: 1,
    log_retention_days: 7,
    features: ["email_notifications", "basic_monitoring", "cron_jobs"],
  },
  STARTER: {
    name: "Starter",
    type: "starter",
    price_monthly: 9,
    price_yearly: 90,
    saving_yearly: 16.7,
    currency: "USD",
    max_monitors: 5,
    max_cron_jobs: 10,
    max_team_members: 5,
    max_workspaces: 2,
    log_retention_days: 30,
    features: [
      "all_in_hobby",
      "email_notifications",
      "slack_notifications",
      "microsoft_teams_notifications",
      "webhook_notifications",
      "custom_domains",
    ],
  },
  PROFESSIONAL: {
    name: "Professional",
    type: "professional",
    price_monthly: 29,
    price_yearly: 290,
    saving_yearly: 16.7,
    currency: "USD",
    max_monitors: 10,
    max_cron_jobs: 20,
    max_team_members: 10,
    max_workspaces: 5,
    log_retention_days: 90,
    features: [
      "all_in_starter",
      "all_notifications",
      "api_access",
      "custom_domains",
      "priority_support",
    ],
  },
};
